---
title:                    FIO
tagline: 
description:              Foundation for Interwallet Operability
url: 
baseurl: 
lang:                     en
logo:                     /assets/img/logo.png
permalink:                "/:title/"

author:
  email:                  info@blacompany.com
  phone:                  +1-800-354-3434
  address:                2030 West River St. <br> New York 52304

favicon:                  /assets/img/favicon.ico

navbar:
  sticky:                 true
  
footer:
  copyright:              "&copy; 2020 FIO"
  link:
    title:                Privacy Policy
    url:                  /privacy-policy/

google_analytics:         GTM-WWSZ8NR

social_networks:
  facebook:               
  flickr: 
  dribbble: 
  github: 
  instagram:              
  linkedin: 
  pinterest: 
  twitter: 
  vimeo: 
  youtube: 

markdown:                 kramdown
highlighter:              rouge
plugins:
- jekyll-seo-tag

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- ".jekyll-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- package-lock.json
- CHANGELOG
- LICENSE
- README
- "/docs"
- "/assets/js/custom.js"

sass:
  style:                  compressed

livereload:               true

# collections:
#   collection_name:
#     output: true
# defaults:
# - scope:
#     path: ''
#     type: collection_name
#   values:
#     layout: collection_name
# - scope:
#     path: ''
#     type: pages
#   values:
#     layout: 
